### ISSUE TITLE
README에 설명 추가 부탁드립니다.

### ISSUE THREAD

**Issue by progrm-github** [moole100/Google-traslate-tts-downloader#1]
프로그램을 실행시키자 FFmpeg를 설치하라는 에러가 발생했습니다.
문서에 FFmpeg 윈도우 빌드를 다운받고 환경 변수를 지정하는 설명을 추가하면 좋겠습니다.

**Comment by SapoKR** [comment]
이슈를 보고
ffmpeg readme를 업로드 하였습니다.
감사드립니다.
